/* Generated by Yosys 0.67+102 (git sha1 07a615a28-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin23.5-clang++ 18.1.8) */

(* hdlname = "MIPS32" *)
(* top =  1  *)
(* src = "processor.v:1.1-152.10" *)
module MIPS32(clk1, clk2);
  (* src = "processor.v:18.11-18.15" *)
  input clk1;
  wire clk1;
  (* src = "processor.v:19.11-19.15" *)
  input clk2;
  wire clk2;
  (* unused_bits = "0" *)
  wire _0_;
  (* unused_bits = "0" *)
  wire _1_;
  (* keep = 32'd1 *)
  IBUF _2_ (
    .I(clk1),
    .O(_0_)
  );
  (* keep = 32'd1 *)
  IBUF _3_ (
    .I(clk2),
    .O(_1_)
  );
endmodule
